### ISSUE TITLE
Why defaultSrc is set to default none?

### ISSUE THREAD

**Issue by genediazjr** [nlf/blankie#11]
I think most of the time defaultSrc is set to self. Would it be possible to set its default value as 'self' instead? Thanks!

**Comment by nlf** [comment]
script, style, image, and connect sources all default to 'self'. the reason default-src defaults to 'none' is in case a new resource type is added that maybe should not have a default. generally speaking you shouldn't need default-src for much of anything

**Comment by genediazjr** [comment]
I see. any chance we can have a default 'self' value for font-src as well?

**Comment by nlf** [comment]
sure, that's reasonable i think

**Comment by genediazjr** [comment]
Nice. I'll wait for it then. Thanks!
