### ISSUE TITLE
Question: CSP for API?

### ISSUE THREAD

**Issue by danactive** [nlf/blankie#14]
Content Security Policy seems ideal for browser security to prevent XSS or browser extension manipulation. What are the benefits for a REST API using hapi.js without HTML, CSS, or JS content?

**Comment by nlf** [comment]
there really isn't any benefit of CSP in a REST API.

CSP is a security feature leveraged by browsers, so unless your REST API is intended to be consumed directly by a browser, it doesn't really make any sense to have CSP on it.
