### ISSUE TITLE
could generateNonces be made more granular?

### ISSUE THREAD

**Issue by travi** [nlf/blankie#16]
I have an app where I would like to use a nonce for one inline script, but allow inline styles with `unsafe-inline`. Leaving `generateNonces` as `true` for the script usage prevents my ability to allow inline for styles.

For context, this is a universal React app using [material-ui](https://github.com/callemall/material-ui), which uses inline styles. The inline script is a simple variable declaration to make the data that was fetched for server rendering available for rehydration on the client. I want to use the nonce for the script since it is safer, but I don't think I can go to that level for the inline styles produced by the react components.

If a nonce was included for the `scriptSrc`, but not for the `styleSrc`, I could make this work. I'm also open to other approaches if there is a better option, but this was the best I could figure out from my investigation.

**Comment by travi** [comment]
@nlf is this a change that you would be open to? i might be able to put a PR together if you're open to the change and could give some thoughts on what you think the the config should look like.

**Comment by nlf** [comment]
yeah, i'd definitely be open to this.

maybe in addition to `generateNonces` we have `generateScriptNonces` and `generateStyleNonces`?

something like this:

if `generateNonces` is true and the other values are unset, we generate both.
if `generateNonces` is true and one of the other values is `false` but the other is unset or `true`, we only skip the `false` one.
if `generateNonces` is false and the other values are unset, we don't generate any nonces.
if `generateNonces` is false and one of the other values is `true` but the other is unset or `false`, we only generate the nonce for the `true` setting.

do you think that allows fine grained enough control?

**Comment by travi** [comment]
yep, i think that's along the lines of what i was thinking

**Comment by travi** [comment]
sorry that it has taken a while to get back to this, but as i look to get a PR together, i'm rethinking how to configure this. 

i think rather than adding `generateScriptNonces` and `generateStyleNonces`, it might be better to stick to only `generateNonces` but allow values of `scriptSrc` and `styleSrc` in addition to the existing boolean values. that should still cover all of the cases we've mentioned, but keeps the implementation simpler and hopefully removes confusion from users by eliminating the need to consider overlapping rules from multiple config items. 

does this change seem reasonable to you, or would you still prefer the approach outlined above?
