### ISSUE TITLE
Allow setting base-uri

### ISSUE THREAD

**Issue by klaemo** [nlf/blankie#19]
Hey there,
I think it would be helpful to be able to set the `base-uri`. Currently I haven't found a way to do that with blankie. Am I missing something?

As per Google's CSP evaluator:
> Missing base-uri allows the injection of base tags. They can be used to set the base URL for all relative (script) URLs to an attacker controlled domain.

Thank you for this plugin!

**Comment by jerome724** [comment]
Nope, not possible atm with Blankie.  You have to set it manually,

plugins/securityHeaders.js (super simple example):
```js
'use strict';
exports.register = (server, options, next) => {
	server.ext('onPreResponse', (req, res) => {
		const set = req.response;

		if (set.header) {
			set.header('Content-Security-Policy', 'base-uri https://example.com;');
		}
		res.continue();
	});
	next();
};

exports.register.attributes = {
	version: '1.0.0',
	name: 'securityHeaders'
};
```
