### ISSUE TITLE
Discussion: Supporting nonce

### ISSUE THREAD

**Issue by evilpacket** [nlf/blankie#3]
Would be nice to start the discussion around supporting nonce as has been done in other similar projects (https://github.com/twitter/secureheaders)

References
- https://github.com/twitter/secureheaders#csp-level-2-features
- https://w3c.github.io/webappsec/specs/content-security-policy/#script-src-the-nonce-attribute

**Comment by nlf** [comment]
looks like it won't be too terribly difficult to implement, so seems like a good idea

**Comment by zeke** [comment]
+1

**Comment by jefflembeck** [comment]
@nlf I'm wondering if you've had any ideas on this subject. If not, are you open to a PR?

**Comment by nlf** [comment]
I had started working on it before a family emergency took me out of town for a while. If you have a PR ready though, go ahead and send it

**Comment by jefflembeck** [comment]
@nlf I don't yet. Came to a spot where we need to throw in an inline without leaving `unsafe-inline` in place, and came to take a look. Will throw something together soon.

**Comment by nlf** [comment]
closed via f746b51
