### ISSUE TITLE
Scooter pulled into @hapi/scooter causing dependency issue

### ISSUE THREAD

**Issue by InfinitySamurai** [nlf/blankie#31]
Hi there,

I'm trying to load blankie into a project, however I'm getting an issue because `Plugin blankie missing dependency scooter`.

When I install the dependency `scooter` it works, however according to the npm scooter itself is deprecated and "This module has moved and is now available at @hapi/scooter".

I went into the `blankie/lib/index.js` file and changed the `dependencies: ['scooter']` in the plugin to be `dependencies: ['@hapi/scooter']` and it also successfully loaded. 

I am currently using confippet in my project and potentially other packages/configuration that could be interfering with this loading appropriately, however this seems to me like it might be an issue going forward.

**Comment by nlf** [comment]
i just published version 4.1.1 which updates to all of the new scoped dependencies

**Comment by InfinitySamurai** [comment]
Thanks so much for fixing this quickly!
