### ISSUE TITLE
Release 4.1.1 as 5.0.0

### ISSUE THREAD

**Issue by nhodges** [nlf/blankie#32]
4.1.1 is now requiring us to explicitly install `@hapi/scooter` which is a breaking change to anyone depending on `^4.1.0`. Is it possible to release this as 5.0.0?

**Comment by brandonburkett** [comment]
I hit this this morning as well!

**Comment by nuri-hodges-ck** [comment]
@nlf 👋

**Comment by nhodges** [comment]
@nlf 👋

**Comment by nhodges** [comment]
@nlf 🎉 🎁 💝 

here's hoping

**Comment by nlf** [comment]
done as 5.0.0
