### ISSUE TITLE
Safari Issues?

### ISSUE THREAD

**Issue by Icehunter** [nlf/blankie#6]
Hi!

Thanks for the great plugin. I've been using blankie/scooter and hapi but for some reason safari never respects what is set.

Safari fails in both hapi 8.x and 9.x.

The error I would see would be something like so:

<img width="1440" alt="screen shot 2015-09-06 at 18 52 42" src="https://cloud.githubusercontent.com/assets/677341/9707878/9efb9de6-54c8-11e5-89ac-7d87657e2366.png">

I was wondering if there is a setting I'm missing?

**Comment by daanvanham** [comment]
Not sure if this is still an issue for you, but I ran into the same problem. Eventually I found this link: https://scotthelme.co.uk/safari-doesnt-like-csp/. 

TL;DR:
> For now, if I want my CSP to work properly in Safari, and if you want yours to work properly too, you will have to leave the scheme in the policy for each source you whitelist. Thanks Apple.

For me it did the trick :) Hopefully it will help you to!

**Comment by nlf** [comment]
i take it this is less about blankie and more about safari's implementation of CSP?

i'm going to close this based on that assumption, but reopen it if i'm wrong
